language: php

php:
  - 7.0

before_script:
  - pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
