language: php

php:
  - 7.0

before_script:
  - pecl -q install mongodb
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist && make sniff

after_script:
  - php vendor/bin/coveralls -v
