language: php

php:
  - 7.0

before_script:
  - pecl install mongodb
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - echo $TRAVIS
  - echo $TRAVIS_JOB_ID
  - php vendor/bin/coveralls -v
